In [1]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence
from torch.optim.lr_scheduler import StepLR
import torch.nn.functional as F
import pandas as pd
import numpy as np
import ast
import cv2
import math
import os
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.metrics import accuracy_score, f1_score
import json
from time import time
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [2]:
username = ""
password =  ""

!git clone https://{username}:{password}@github.itu.dk/sosk/TennisTrajectoryReconstruction.git
os.chdir('/kaggle/working/TennisTrajectoryReconstruction/')
from TennisTrajectoryReconstruction.Utils.Reconstruction3D.Reconstruction3D_utils import create_3d_trajectory, create_3d_trajectory_with_spin, project_points_torch, get_court_dimension, average_distance, error_distance_landing, ball_hits_court, calculate_accuracy, calculate_f1_macro
from TennisTrajectoryReconstruction.Utils.Visualisations.Visualisation_utils import plot_tennis_court
from TennisTrajectoryReconstruction.Utils.CameraParams.CameraParams_utils import find_poles_and_corners_world
os.chdir('/kaggle/working')

Cloning into 'TennisTrajectoryReconstruction'...
remote: Enumerating objects: 441, done.
remote: Counting objects: 100% (162/162), done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 441 (delta 60), reused 158 (delta 60), pack-reused 279
Receiving objects: 100% (441/441), 5.40 MiB | 20.32 MiB/s, done.
Resolving deltas: 100% (164/164), done.


In [3]:
class CustomDataset_real(Dataset):
    def __init__(self, input_data, camera_params, predicted):
        self.input_data = input_data
        self.camera_params = camera_params
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.homography_matrix = None
        self.predicted = predicted

    def __len__(self):
        return len(self.input_data)

    def __getitem__(self, idx):
        

        shot_id =  self.input_data.index[idx] - 1
        
        game_id = self.input_data.iloc[shot_id]['game']
        clip_id = self.input_data.iloc[shot_id]['clip']
        start = self.input_data.iloc[shot_id]['start']
        end = self.input_data.iloc[shot_id]['end']
        
        
        mtx, dist, rvecs, tvecs, rotation_matrix, homography = self.prepare_camera_parameters(self.camera_params, game_id, clip_id)

        player1, player2 = self.find_players(game_id, clip_id, start, end)
        #player1, player2, player1_homography, player2_homography = self.prepare_poses(game_id, clip_id, start, end)
        homography_matrix = torch.tensor(self.homography_matrix, device=self.device)
        
        
        if self.predicted:
            x = eval(self.input_data.iloc[shot_id]['x_WASB'])
            y = eval(self.input_data.iloc[shot_id]['y_WASB'])
        else:
            x = self.input_data.iloc[shot_id]['x_true']
            y = self.input_data.iloc[shot_id]['y_true']
            

        
        train = torch.tensor([[a/1280, b/720] for a, b in zip(x, y)], device=self.device)
        
        court_corners = self.get_corners(game_id, clip_id)
        
        if train.numel() == 0:
            return None
#         print(rotation_matrix)
        # train.permute(1,0)
        #return train, mtx, dist, rvecs, tvecs, rotation_matrix, player1, player2, player1_homography, player2_homography, court_corners, homography_matrix, (idx)
        return train, mtx, dist, rvecs, tvecs, rotation_matrix, court_corners, (shot_id), player1, player2, homography_matrix, game_id, clip_id
    
    def prepare_camera_parameters(self, camera_parameters, game_id, clip_id):
        return_camera_params = self.camera_params[(self.camera_params['game'] == game_id) & (self.camera_params['clip'] == clip_id)].iloc[0]
        
        mtx = return_camera_params['camera_matrix']
        dist = return_camera_params['dist']
        rvecs = return_camera_params['rotation_vector']
        tvecs = return_camera_params['translation_vector']
        #print(type(eval(return_camera_params['homography_matrix'])))
        homography_matrix = eval(return_camera_params['homography_matrix'])
        
        self.homography_matrix = np.array(homography_matrix)
#         print(rvecs)
        rotation_matrix, _ = cv2.Rodrigues(np.array(rvecs))

        return (torch.tensor(mtx, requires_grad=True, device=self.device), torch.tensor(dist, requires_grad=True, device=self.device), torch.tensor(rvecs, requires_grad=True, device=self.device), 
                torch.tensor(tvecs, requires_grad=True, device=self.device), torch.tensor(rotation_matrix, requires_grad=True, device=self.device),
                torch.tensor(homography_matrix, requires_grad=True, device=self.device))
    
        
    def find_players(self, game_id, clip_id, start, end):
        
        
        path = f"/kaggle/input/filtered-poses/Dataset/{game_id}/{clip_id}/data.csv"
        pose_df = pd.read_csv(path).drop(columns=['Unnamed: 0', 'ball_x', 'ball_y', 'hits']).iloc[start:end].to_numpy()
        
        player1 = pose_df[:, 0:34]
        player2 = pose_df[:, 34: ]
        
        
        player1_left_foot = player1[:, 30:32]
        player1_right_foot = player1[:, 32:34]
        player1_mid = np.array(((player1_left_foot[:, 0] + player1_right_foot[:, 0]) / 2, (player1_left_foot[:, 1] + player1_right_foot[:, 1]) / 2)).T

        player2_left_foot = player2[:, 30:32]
        player2_right_foot = player2[:, 32:34]
        player2_mid = np.array(((player2_left_foot[:, 0] + player2_right_foot[:, 0]) / 2, (player2_left_foot[:, 1] + player2_right_foot[:, 1]) / 2)).T
        

        
        ground_plane_coords_player1 = cv2.perspectiveTransform(player1_mid[0].reshape(1, -1, 2), self.homography_matrix).squeeze()
        ground_plane_coords_player2 = cv2.perspectiveTransform(player2_mid[0].reshape(1, -1, 2), self.homography_matrix).squeeze()

        ground_plane_coords_player1 = np.append(ground_plane_coords_player1, 1.5)
        ground_plane_coords_player2 = np.append(ground_plane_coords_player2, 1.5)
        
        court_length, court_width, half_court_length, half_court_width, net_height_middle, net_height_sides = get_court_dimension()
        


        ground_plane_coords_player1[0] = ground_plane_coords_player1[0] / (half_court_width + 1)
        ground_plane_coords_player1[1] = ground_plane_coords_player1[1] / (half_court_length + 1)
        ground_plane_coords_player1[2] = ground_plane_coords_player1[2] / 3

        ground_plane_coords_player2[0] = ground_plane_coords_player2[0] / (half_court_width + 1)
        ground_plane_coords_player2[1] = ground_plane_coords_player2[1] / (half_court_length + 1)
        ground_plane_coords_player2[2] = ground_plane_coords_player2[2] / 3
        
        return torch.tensor(ground_plane_coords_player1, requires_grad=True, device=self.device), torch.tensor(ground_plane_coords_player2, requires_grad=True, device=self.device)

        
    def get_corners(self, game_id, clip_id):
        
        path = f'/kaggle/input/court-detection-coordinates/Dataset/{game_id}/{clip_id}/court.csv'
        
        court_df = pd.read_csv(path)
        court_coordinates = court_df[court_df['point'].isin([0, 1, 2, 3])][['x-coordinate', 'y-coordinate']].to_numpy().astype(np.float64)
        
        court_coordinates[:, 0] = court_coordinates[:, 0] / 1280
        court_coordinates[:, 1] = court_coordinates[:, 1] / 720
        
        
        return torch.tensor(court_coordinates, requires_grad=True, device=self.device,dtype=torch.float)
        


In [4]:
class CustomDataset_Synthetic(Dataset):
    def __init__(self, input_data, camera_params, sampled_cam_params = False):
        self.input_data = input_data
        self.camera_params = camera_params
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.homography_matrix = None
        self.sampled_params = sampled_cam_params

    def __len__(self):
        return len(self.input_data)

    def __getitem__(self, idx):
        
        
        
        shot_id =  self.input_data.index[idx] - 1
        game_id = self.input_data.iloc[idx]['game']
        clip_id = self.input_data.iloc[idx]['clip']
        
        starting_params = torch.tensor(eval(self.input_data.iloc[idx]['starting_params'])) 
        
        
        projection = torch.tensor(eval(self.input_data.iloc[idx]['projection']))
        
        projection[:, 0] = projection[:, 0] / 1280
        projection[:, 1] = projection[:, 1] / 720
        
        start_position =  torch.tensor(eval(self.input_data.iloc[idx]['trajectory3D']))[0]
        end_position =  torch.tensor(eval(self.input_data.iloc[idx]['trajectory3D']))[1]
        
        
        court_length, court_width, half_court_length, half_court_width, net_height_middle, net_height_sides = get_court_dimension()
        
        
        
        start_position[0] = start_position[0] / (half_court_width + 1)
        start_position[1] = start_position[1] / (half_court_length + 1)
        start_position[2] = start_position[2] / 3
        
        end_position[0] = end_position[0] / (half_court_width + 1)
        end_position[1] = end_position[1] / (half_court_length + 1)
        end_position[2] = end_position[2] / 3
        
        
        mtx, dist, rvecs, tvecs, rotation_matrix, homography = self.prepare_camera_parameters(self.camera_params, game_id, clip_id)
        if self.sampled_params:
            court_coordinates = find_poles_and_corners_world()
            corner = torch.tensor(court_coordinates[-4:])
            court_corners = project_points_torch(corner, rotation_matrix, tvecs, mtx, dist)
            
        else:
            court_corners = self.get_corners(game_id, clip_id)
        
        
        #if train.numel() == 0:
        #    return None
#         print(rotation_matrix)
        # train.permute(1,0)

        return starting_params, projection,  mtx, dist, rvecs, tvecs, rotation_matrix, court_corners, (shot_id), start_position, end_position, homography, game_id, clip_id
    
    def prepare_camera_parameters(self, camera_parameters, game_id, clip_id):
        return_camera_params = self.camera_params[(self.camera_params['game'] == game_id) & (self.camera_params['clip'] == clip_id)].iloc[0]
        
        mtx = return_camera_params['camera_matrix']
        dist = return_camera_params['dist']
        rvecs = return_camera_params['rotation_vector']
        tvecs = return_camera_params['translation_vector']
        #print(type(eval(return_camera_params['homography_matrix'])))
        homography_matrix = eval(return_camera_params['homography_matrix'])
        
        self.homography_matrix = np.array(homography_matrix)
#         print(rvecs)
        rotation_matrix, _ = cv2.Rodrigues(np.array(rvecs))

        return (torch.tensor(mtx, requires_grad=True, device=self.device), torch.tensor(dist, requires_grad=True, device=self.device), torch.tensor(rvecs, requires_grad=True, device=self.device), 
                torch.tensor(tvecs, requires_grad=True, device=self.device), torch.tensor(rotation_matrix, requires_grad=True, device=self.device),
                torch.tensor(homography_matrix, requires_grad=True, device=self.device))
    
    def get_corners(self, game_id, clip_id):
        
        path = f'/kaggle/input/court-detection-coordinates/Dataset/{game_id}/{clip_id}/court.csv'
        
        court_df = pd.read_csv(path)
        court_coordinates = court_df[court_df['point'].isin([0, 1, 2, 3])][['x-coordinate', 'y-coordinate']].to_numpy().astype(np.float64)
        
        court_coordinates[:, 0] = court_coordinates[:, 0] / 1280
        court_coordinates[:, 1] = court_coordinates[:, 1] / 720
        
        
        return torch.tensor(court_coordinates, requires_grad=True, device=self.device,dtype=torch.float)

In [5]:
def pad_tensor(tensor, desired_rows):
    current_rows = tensor.shape[0]
    rows_to_pad = desired_rows - current_rows
    return F.pad(tensor, (0, 0, 0, rows_to_pad), value=-1, mode='constant')


# Define a custom converter function
def parse_list(string):
    try:
        # Use ast.literal_eval to safely parse the string representation of a list
        return ast.literal_eval(string)
    except (SyntaxError, ValueError):
        # If parsing fails, return None or any other default value as needed
        return None
    
def custom_collate_synthetic(batch, GRU):
    # Extract data from the batch
    starting_params, projection,  mtx, dist, rvecs, tvecs, rotation_matrix, court_corners, (shot_id), start_position, end_position, homography, game_id, clip_id = zip(*batch)
    
    # Pad inputs differently for each batch
    #max_input_length = max(len(seq[:, 1]) for seq in inputs)
    #padded_projection = [torch.nn.functional.pad(seq, (0, 0, 0, 50 - len(seq[:, 1])), value=-1, mode='constant') for seq in projection]
    #padded_projection = torch.stack(padded_projection)
    if GRU:
        max_input_length = max(len(seq[:, 1]) for seq in inputs)
        padded_projection = [torch.nn.functional.pad(seq, (0, 0, 0, max_input_length - len(seq[:, 1])), value=-1, mode='constant') for seq in projection]
        padded_projection = torch.stack(padded_projection)
    else:
        padded_inputs = [pad_tensor(seq, 50) for seq in projection]
        #padded_projection = [torch.nn.functional.pad(seq, (0, 0, 0, 50 - len(seq[:, 1])), value=-1, mode='constant') for seq in projection]
        padded_projection = torch.stack(padded_inputs)

    
    # Stack other data
    stacked_mtx = torch.stack(mtx).to(device)
    stacked_dist = torch.stack(dist).to(device)
    stacked_rvecs = torch.stack(rvecs).to(device)
    stacked_tvecs = torch.stack(tvecs).to(device)
    stacked_rotation_matrix = torch.stack(rotation_matrix).to(device)
    stacked_starting_params = torch.stack(starting_params).to(device)
    stacked_start_position = torch.stack(start_position).to(device)
    stacked_end_position = torch.stack(end_position).to(device)
    stacked_homography = torch.stack(homography).to(device)
    #game_id = torch.stack(game_id)
    #clip_id = torch.stack(clip_id)
    
    #stacked_player1 = torch.stack(player1)
    #stacked_player2 = torch.stack(player2)
    stacked_court_corners = torch.stack(court_corners).to(device)
    
    # Return padded inputs and other data
    return (stacked_starting_params, padded_projection, stacked_mtx, stacked_dist, stacked_rvecs, stacked_tvecs, stacked_rotation_matrix, 
            stacked_court_corners, shot_id, stacked_start_position, stacked_end_position, stacked_homography, game_id, clip_id)

# Custom collate function to handle sequences of varying lengths
def custom_collate_real(batch, GRU):
    for i in batch:
        if i is None:
            return None
    inputs, mtx, dist, rvecs, tvecs, rotation_matrix, court_corners, (shot_id), player1, player2, homography_matrix, game_id, clip_id = zip(*batch)
    if GRU:
        max_input_length = max(len(seq[:, 1]) for seq in inputs)
        padded_inputs = [torch.nn.functional.pad(seq, (0, 0, 0, max_input_length - len(seq[:, 1])), value=-1, mode='constant') for seq in inputs]
        padded_inputs = torch.stack(padded_inputs)
    else:
        padded_inputs = [pad_tensor(seq, 50) for seq in inputs]
        padded_inputs = torch.stack(padded_inputs)

    return (padded_inputs, torch.stack(mtx), torch.stack(dist), torch.stack(rvecs), torch.stack(tvecs), 
            torch.stack(rotation_matrix), torch.stack(court_corners), shot_id, torch.stack(player1), torch.stack(player2), torch.stack(homography_matrix), game_id, clip_id)

In [6]:
def normalise_starting_params(starting_params : str):
    
    court_length, court_width, half_court_length, half_court_width, net_height_middle, net_height_sides = get_court_dimension()
    starting_params = np.array(eval(starting_params))
    
    starting_params[0] = starting_params[0] / (half_court_width + 1)
    starting_params[1] = starting_params[1] / (half_court_length + 1)
    starting_params[2] = starting_params[2] / 3
    starting_params[3] = starting_params[3] / 4
    starting_params[4] = starting_params[4] / 30
    starting_params[5] = starting_params[5] / 5
    
    if len(starting_params) > 6:
        starting_params[6] = starting_params[6] / (10*2*math.pi)
        starting_params[7] = starting_params[7] / (1*2*math.pi)
        starting_params[8] = starting_params[8] / (5*2*math.pi)
    
    return str(list(starting_params))

def upscale_starting_params(starting_params : torch.tensor):
    court_length, court_width, half_court_length, half_court_width, net_height_middle, net_height_sides = get_court_dimension()
    
    starting_params[0] = starting_params[0] * (half_court_width + 1)
    starting_params[1] = starting_params[1] * (half_court_length + 1)
    starting_params[2] = starting_params[2] * 3
    starting_params[3] = starting_params[3] * 4
    starting_params[4] = starting_params[4] * 30
    starting_params[5] = starting_params[5] * 5
    
    
    if len(starting_params) > 6:
        starting_params[6] = starting_params[6] * (10*2*math.pi)
        starting_params[7] = starting_params[7] * (1*2*math.pi)
        starting_params[8] = starting_params[8] * (5*2*math.pi)
    
    return starting_params

def upscale_starting_params_batch(starting_params : torch.tensor):
    court_length, court_width, half_court_length, half_court_width, net_height_middle, net_height_sides = get_court_dimension()
    
    starting_params[:,0] = starting_params[:,0] * (half_court_width + 1)
    starting_params[:,1] = starting_params[:,1] * (half_court_length + 1)
    starting_params[:,2] = starting_params[:,2] * 3
    starting_params[:,3] = starting_params[:,3] * 4
    starting_params[:,4] = starting_params[:,4] * 30
    starting_params[:,5] = starting_params[:,5] * 5
    
    if starting_params.shape[1] > 6:
        starting_params[:,6] = starting_params[:,6] * (10*2*math.pi)
        starting_params[:,7] = starting_params[:,7] * (1*2*math.pi)
        starting_params[:,8] = starting_params[:,8] * (5*2*math.pi)
    
    return starting_params
    

In [7]:
def fix_trajectory(traj):
    
    
    if traj[0] <= 0:
        vals_to_change = []
        i = 0
        
        while traj[i] <= 0:
            vals_to_change.append(i)
            i += 1
        
        for j in vals_to_change:
            traj[j] = traj[i]
        
            
    
    for i in range(len(traj)):
        if traj[i] <= 0:
            traj[i] = traj[i-1]
        
    return traj


def clean_true(df):
    
    v_to_remove = ["nan", " ", " nan"]
    df["x_true"] = df.apply(lambda row: [float(v) if v not in v_to_remove else 0 for v in row["x_true"].strip("[]").split(", ")], axis=1)
    df["y_true"] = df.apply(lambda row: [float(v) if v not in v_to_remove else 0 for v in row["y_true"].strip("[]").split(", ")], axis=1)
    
    df['x_true'] = df['x_true'].apply(lambda row : fix_trajectory(row))
    df['y_true'] = df['y_true'].apply(lambda row : fix_trajectory(row))
    df = df.reset_index()
    df = df.drop([432, 131, 483, 233, 440, 6, 420, 34, 317, 451, 272, 438, 342, 430])
    print(len(df))
    df = df[df['x_true'].apply(lambda row : len(row) > 5)]
    print(len(df))
    return df.reset_index()

def clean_predicted(ball_df):
    ball_df = ball_df[ball_df["x_WASB"].apply(lambda x: len(x)  > 3)].reset_index()
    ball_df = ball_df.drop([293, 141 , 462, 460, 443, 471, 35, 364, 6])
    ball_df['x_WASB'] = ball_df['x_WASB'].apply(lambda row : str(fix_trajectory(eval(row))))
    ball_df['y_WASB'] = ball_df['y_WASB'].apply(lambda row : str(fix_trajectory(eval(row))))
    print(len(ball_df))
    ball_df = ball_df[ball_df['x_WASB'].apply(lambda row : len(eval(row)) > 5)]
    print(len(ball_df))
    return ball_df.reset_index()

In [8]:
convert_dict = {'camera_matrix': parse_list,
               'dist': parse_list,
               'rotation_vector': parse_list,
               'translation_vector':parse_list}

camera_params_train  = pd.read_csv('/kaggle/input/camera-parameters/camera_paramters.csv', 
                      converters=convert_dict).drop(columns=['Unnamed: 0'])

ball_df_true = clean_true(pd.read_csv('/kaggle/input/segmented-shots-predictions/true_segmented_shots.csv', 
                      converters=convert_dict).drop(columns=['Unnamed: 0']))

ball_df_pred = clean_predicted(pd.read_csv('/kaggle/input/segmented-shots-predictions/predicted_segmented_shots.csv', 
                      converters=convert_dict).drop(columns=['Unnamed: 0']))

synthetic_df = pd.read_csv('/kaggle/input/synthetic-tennis-trajectories/10000_synthetic_shots.csv', 
                      converters=convert_dict).drop(columns=['Unnamed: 0'])

synthetic_df_spin = pd.read_csv('/kaggle/input/synthetic-tennis-trajectories/10000_synthetic_shots_spin.csv', 
                      converters=convert_dict).drop(columns=['Unnamed: 0'])

synthetic_df_spin.loc[:, 'starting_params'] = synthetic_df_spin['starting_params'].apply(lambda row: normalise_starting_params(row))

synthetic_df.loc[:, 'starting_params'] = synthetic_df['starting_params'].apply(lambda row: normalise_starting_params(row))

# Synthetic without spin
batch_size = 64
synthetic_train = synthetic_df[~synthetic_df['game'].isin(['game1', 'game8'])]
syn_dataset_train = CustomDataset_Synthetic(synthetic_train, camera_params_train)
syn_loader_train_NN = DataLoader(syn_dataset_train, batch_size=batch_size, shuffle=True, collate_fn=lambda batch: custom_collate_synthetic(batch, GRU=False))

synthetic_test = synthetic_df[synthetic_df['game'].isin(['game1', 'game8'])]
syn_dataset_val = CustomDataset_Synthetic(synthetic_test, camera_params_train)
syn_loader_val_NN = DataLoader(syn_dataset_val, batch_size=batch_size, shuffle=True, collate_fn=lambda batch: custom_collate_synthetic(batch, GRU=False))

# Synthetic without spin
batch_size = 64
synthetic_train_spin = synthetic_df_spin[~synthetic_df_spin['game'].isin(['game1', 'game8'])]
syn_dataset_train_spin = CustomDataset_Synthetic(synthetic_train_spin, camera_params_train)
syn_loader_train_NN_spin = DataLoader(syn_dataset_train_spin, batch_size=batch_size, shuffle=True, collate_fn=lambda batch: custom_collate_synthetic(batch, GRU=False))

synthetic_test_spin = synthetic_df_spin[synthetic_df_spin['game'].isin(['game1', 'game8'])]
syn_dataset_val_spin = CustomDataset_Synthetic(synthetic_test_spin, camera_params_train)
syn_loader_val_NN_spin = DataLoader(syn_dataset_val_spin, batch_size=batch_size, shuffle=True, collate_fn=lambda batch: custom_collate_synthetic(batch, GRU=False))


# Real data
train_df_true = ball_df_true[~ball_df_true['game'].isin(['game1', 'game8'])]
real_train_dataset_true = CustomDataset_real(train_df_true, camera_params_train, predicted = False)
real_train_loader_NN_true = DataLoader(real_train_dataset_true, batch_size=1, shuffle=True, collate_fn=lambda batch : custom_collate_real(batch, GRU=False))

train_df_pred = ball_df_pred[~ball_df_pred['game'].isin(['game1', 'game8'])]
real_train_dataset_pred = CustomDataset_real(train_df_pred, camera_params_train, predicted = True)
real_train_loader_NN_pred = DataLoader(real_train_dataset_pred, batch_size=1, shuffle=True, collate_fn=lambda batch : custom_collate_real(batch, GRU=False))

# real test
test_df_true = ball_df_true[ball_df_true['game'].isin(['game1', 'game8'])]
real_test_dataset_true = CustomDataset_real(test_df_true, camera_params_train, predicted = False)
real_test_loader_NN_true = DataLoader(real_test_dataset_true, batch_size=1, shuffle=True, collate_fn=lambda batch : custom_collate_real(batch, GRU=False))

test_df_pred = ball_df_pred[ball_df_pred['game'].isin(['game1', 'game8'])]
real_test_dataset_pred = CustomDataset_real(test_df_pred, camera_params_train,predicted = True)
real_test_loader_NN_pred = DataLoader(real_test_dataset_pred, batch_size=1, shuffle=True, collate_fn=lambda batch : custom_collate_real(batch, GRU=False))

# real all
real_all_dataset_true = CustomDataset_real(ball_df_true, camera_params_train, predicted = False)
real_all_loader_NN_true = DataLoader(real_all_dataset_true, batch_size=1, shuffle=True, collate_fn=lambda batch : custom_collate_real(batch, GRU=False))

real_all_dataset_pred = CustomDataset_real(ball_df_pred, camera_params_train,predicted = True)
real_all_loader_NN_pred = DataLoader(real_all_dataset_pred, batch_size=1, shuffle=True, collate_fn=lambda batch : custom_collate_real(batch, GRU=False))


492
487
508
479


# Create Model

In [9]:
class CustomModel(nn.Module):
    def __init__(self, input_size, output_size, dropout_prob=0.2):
        super(CustomModel, self).__init__()
        
        # Define fully connected layers
        self.fc1 = nn.Linear(input_size, 256)
        self.fc2 = nn.Linear(256, 512)
        self.fc21 = nn.Linear(512, 1028)
        self.fc22 = nn.Linear(1028, 512)
        self.fc3 = nn.Linear(512, 256)
        self.fc4 = nn.Linear(256, 128)
        #self.fc3 = nn.Linear(256, 128)
        self.final = nn.Linear(128, output_size)
        
        # Define batch normalization layers
        self.bn1 = nn.BatchNorm1d(256)
        self.bn2 = nn.BatchNorm1d(512)
        self.bn21 =  nn.BatchNorm1d(1028)
        self.bn22 =  nn.BatchNorm1d(512)
        self.bn3 = nn.BatchNorm1d(256)
        self.bn4 = nn.BatchNorm1d(128)

        # Define dropout layers
        self.dropout1 = nn.Dropout(dropout_prob)
        self.dropout2 = nn.Dropout(dropout_prob)
        self.dropout21 = nn.Dropout(dropout_prob)
        self.dropout22 = nn.Dropout(dropout_prob)
        self.dropout3 = nn.Dropout(dropout_prob)
        self.dropout4 = nn.Dropout(dropout_prob)

        # Weight initialization
        nn.init.xavier_uniform_(self.fc1.weight)
        nn.init.xavier_uniform_(self.fc2.weight)
        nn.init.xavier_uniform_(self.fc3.weight)
        nn.init.xavier_uniform_(self.fc4.weight)


    def forward(self, x):
        
        # without normalization
        x = torch.relu(self.bn1(self.fc1(x)))
        x = self.dropout1(x)
        x = torch.relu(self.bn2(self.fc2(x)))
        x = self.dropout2(x)
        x = torch.relu(self.bn21(self.fc21(x)))
        x = self.dropout21(x)
        x = torch.relu(self.bn22(self.fc22(x)))
        x = self.dropout22(x)
        x = torch.relu(self.bn3(self.fc3(x)))
        x = self.dropout3(x)
        x = torch.relu(self.bn4(self.fc4(x)))
        x = self.dropout4(x)
        x = self.final(x)

        return x

    

In [10]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from tqdm import tqdm
from sklearn.metrics import accuracy_score

def train_syn(num_epochs : int, lr : float, use_court : bool, use_cam_params : bool, use_positions : bool, spin : bool, model_):

    input_size = 100
    output_size = 6
    
    data_loader = syn_loader_train_NN
    val_loader = syn_loader_val_NN
    
    if spin:
        output_size += 3
        data_loader = syn_loader_train_NN_spin
        val_loader = syn_loader_val_NN_spin
    if use_court:
        input_size += 4*2
    if use_cam_params:
        input_size += 3*3 + 3 + 3*3 + 5
    if use_positions:
        input_size += 3*2
    
    losses = []
    val_loss = []
    mse_pr_items = []


    model = model_(input_size, output_size).to(device)
    
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)
    scheduler = StepLR(optimizer, step_size=2, gamma=0.5)

    # Iterate over epochs
    for epoch in range(num_epochs):
        
        predicted_tiles = []
        true_tiles = []
        
        model.train()  # Set the model to training mode
        running_loss = 0.0
        
            
        

        # Iterate over batches in the train_loader
        for batch in tqdm(data_loader, desc=f'Epoch {epoch + 1}/{num_epochs}', leave=False):

            starting_params, projection,  mtx, dist, rvecs, tvecs, rotation_matrix, court_corners, (shot_id), start_position, end_position, homography, game_id, clip_id = batch
            
        
            
            
            concatted_input = projection.view(-1, 2*50).to(device)
            
            if use_court:
                concatted_court = court_corners.view(-1, 4*2).to(starting_params.device)
                concatted_input = torch.cat((concatted_court, concatted_input), dim=1)
            if use_cam_params:
                camera_matrix = mtx.view(-1, 3*3).to(starting_params.device)
                translation_matrix = tvecs.view(-1, 3).to(starting_params.device)
                rotation = rotation_matrix.view(-1, 3*3).to(starting_params.device)
                distortion = dist.view(-1, 5).to(starting_params.device)
                concatted_params = torch.cat((camera_matrix, translation_matrix, rotation, distortion), dim=1)
                concatted_input = torch.cat((concatted_params, concatted_input), dim=1).to(starting_params.device)
            if use_positions:
                concatted_positions = torch.cat((start_pos, end_pos)).view(-1, 3*2)
                concatted_input = torch.cat((concatted_positions, concatted_input), dim=1).to(starting_params.device)
                
                
            
                
                

            optimizer.zero_grad()  # Zero the gradients
            # Forward pass

            outputs = model(concatted_input.float())
            
            
            # Calculate loss
            loss = criterion(outputs, starting_params)

            # Backward pass
            loss.backward()

            # Update weights
            optimizer.step()

            # Update running loss
            running_loss += loss.item()

        # Validation phase
        model.eval()
        val_loss = 0.0
        correct = 0
        total = 0
        with torch.no_grad():
            for batch in tqdm(val_loader, desc=f'Epoch {epoch + 1}/{num_epochs}', leave=False):
                starting_params, projection,  mtx, dist, rvecs, tvecs, rotation_matrix, court_corners, (shot_id), start_position, end_position, homography, game_id, clip_id = batch
            
            
                concatted_input = projection.view(-1, 2*50).to(device)

                if use_court:
                    concatted_court = court_corners.view(-1, 4*2).to(starting_params.device)
                    concatted_input = torch.cat((concatted_court, concatted_input), dim=1)
                if use_cam_params:
                    camera_matrix = mtx.view(-1, 3*3).to(starting_params.device)
                    translation_matrix = tvecs.view(-1, 3).to(starting_params.device)
                    rotation = rotation_matrix.view(-1, 3*3).to(starting_params.device)
                    distortion = dist.view(-1, 5).to(starting_params.device)
                    concatted_params = torch.cat((camera_matrix, translation_matrix, rotation, distortion), dim=1)
                    concatted_input = torch.cat((concatted_params, concatted_input), dim=1).to(starting_params.device)
                if use_positions:
                    concatted_positions = torch.cat((start_pos, end_pos)).view(-1, 3*2)
                    concatted_input = torch.cat((concatted_positions, concatted_input), dim=1).to(starting_params.device)
                    
                outputs = model(concatted_input.float())
                #outputs = upscale_starting_params_batch(outputs)
                
                #labels = upscale_starting_params_batch(starting_params)
                #labels = 
                loss = torch.sqrt(criterion(outputs, starting_params))
                val_loss += loss.item()
                
                # Calculate MSE per item in each batch
                mse_per_item = torch.sqrt(torch.mean((outputs - starting_params) ** 2, dim=0))
                mse_pr_items.append(mse_per_item)
                


        avg_val_loss = val_loss / len(syn_loader_val_NN)
        loss_pr_item = torch.mean(torch.stack(mse_pr_items),dim=0)# / len(syn_loader_val_NN)
        print(loss_pr_item)

        scheduler.step()

        epoch_loss = running_loss / len(syn_loader_train_NN.dataset)
        losses.append(epoch_loss)

        print(f'Epoch {epoch + 1}/{num_epochs}, Train Loss: {epoch_loss:.4f}')
        print(f"Epoch {epoch+1}/{num_epochs}, Validation Loss: {avg_val_loss}")
    return model, losses


In [11]:
def predict_NN(data_loader : DataLoader, use_court : bool, use_cam_params : bool, use_positions : bool, synthetic_data : bool, spin : bool, model):
    
    mse_loss = nn.MSELoss()
    
    game_n = []
    clip_n = []
    shot_n = []
    mse_n = []
    rmse_n = []
    pred_tiles = [] 
    true_tiles = []
    landing_error = []
    predicted_3D_traj = []
    start_errors = []
    
    trajectory_distance = []


    
    model.eval()
    with torch.no_grad():
        for batch in data_loader:
            
            if not synthetic_data:
                projection, mtx, dist, rvecs, tvecs, rotation_matrix, court_corners, shot_id, player1, player2, homography, game_id, clip_id = batch
            else:
                starting_params, projection,  mtx, dist, rvecs, tvecs, rotation_matrix, court_corners, (shot_id), start_position, end_position, homography, game_id, clip_id = batch
                
            
            concatted_input = projection.view(-1, 2*50).to(device)
            
            if use_court:
                concatted_court = court_corners.view(-1, 4*2)#.to(projection.device)
                
                concatted_input = torch.cat((concatted_court, concatted_input), dim=1)
                
            if use_cam_params:
                camera_matrix = mtx.view(-1, 3*3)
                translation_matrix = tvecs.view(-1, 3)
                rotation = rotation_matrix.view(-1, 3*3)
                distortion = dist.view(-1, 5)
                concatted_params = torch.cat((camera_matrix, translation_matrix, rotation, distortion), dim=1)
                concatted_input = torch.cat((concatted_params, concatted_input), dim=1)
            if use_positions:
                concatted_players = torch.cat((player1, player2)).view(-1, 6)
                concatted_input = torch.cat((concatted_players, concatted_input), dim=1)
                
            #print(concatted_input.float().device)

            preds = model(concatted_input.float())


            for i in range(len(batch[0])):
                
                game_n.append(game_id[i])
                clip_n.append(clip_id[i])
                shot_n.append(shot_id[i])
                
                #camera_matrices.append(mtx[i])
                #distortion_coefficients.append(dist[i])
                #translation_vectors.append(tvecs[i])
                #rotational_matrices.append(rotation_matrix[i])
                
                if synthetic_data:
                    
                    
                    curr_input = projection[i]

                    mask = curr_input != -1
                    labels = curr_input[mask].view(1,-1,2).to(device)
                    
                    
                    
                    labels[:,:, 0] *= 1280
                    labels[:,:,1] *= 720
                    #true_trajectories.append(labels)
                    
                    
                    N = labels.shape[1]
                    
                    prediction = upscale_starting_params(preds[i])
                    true_start = upscale_starting_params(starting_params[i])
                    
                    squarred_error = (preds[i]-starting_params[i])**2
                    start_errors.append([i.item() for i in squarred_error])
                    
                    
                    if spin:
                        pred_traj = create_3d_trajectory_with_spin(prediction.view(1, 9), N)
                        true_3D_traj = create_3d_trajectory_with_spin(true_start.view(1, 9), N)
                    else:
                        pred_traj = create_3d_trajectory(prediction.view(1, 6), N)
                        true_3D_traj = create_3d_trajectory(true_start.view(1, 6), N)
                            
                    predicted_3D_traj.append(pred_traj.cpu().tolist())
                    pred_projected_path = project_points_torch(pred_traj.to(device), rotation_matrix[i].to(device), tvecs[i].to(device), mtx[i].to(device), dist[i].to(device))
                    

                    pred_tile, true_tile = ball_hits_court(pred_traj, labels, homography[i].to(device))
                    pred_tiles.append(pred_tile)
                    true_tiles.append(true_tile)
                    
                    

                    lan_error = error_distance_landing(pred_traj, labels, homography[i].to(device))
                    landing_error.append(lan_error)
                    
                    mse = mse_loss(pred_projected_path, labels[0])
                    mse_n.append(mse.item())
                    rmse = torch.sqrt(mse)
                    rmse_n.append(rmse.item())
                    
                    

                    
                    avg_dist = average_distance(pred_traj.cpu(), true_3D_traj.cpu())
                    trajectory_distance.append(avg_dist)
                    
                else:
                    

                    curr_input = projection[i]


                    mask = curr_input != -1
                    non_padded_input = curr_input[mask].view(1,-1,2)


                    N = non_padded_input.shape[1]


                    labels = non_padded_input#.detach().cpu().numpy()

                    #true_trajectories.append(labels)

                    labels[:,:, 0] *= 1280
                    labels[:,:,1] *= 720


                    prediction = upscale_starting_params(preds[i])
                    #outputs.append(prediction)
                    
                    if spin:
                        new_traj = create_3d_trajectory_with_spin(prediction.view(1, 9), N)
                    else:
                        new_traj = create_3d_trajectory(prediction.view(1, 6), N)
                
                    predicted_3D_traj.append(new_traj.cpu().tolist())
                    projected_path = project_points_torch(new_traj, rotation_matrix[i], tvecs[i], mtx[i], dist[i])
                    
                    
                    pred_tile, true_tile = ball_hits_court(new_traj, labels, homography[i].to(device))
                    pred_tiles.append(pred_tile)
                    true_tiles.append(true_tile)

                    lan_error = error_distance_landing(new_traj, labels, homography[i].to(device))
                    landing_error.append(lan_error)
                    
                    mse = mse_loss(projected_path, labels[0])
                    mse_n.append(mse.item())
                    rmse = torch.sqrt(mse)
                    rmse_n.append(rmse.item())

                    
    if not synthetic_data:
        result_df = pd.DataFrame(list(zip(game_n, clip_n, shot_n, mse_n, rmse_n, pred_tiles, true_tiles, landing_error, predicted_3D_traj)),
                   columns =['Game', 'Clip', "Shot Number", "MSE", "RMSE", "predicted_tiles", "true_tiles", 'landing_error', 'predicted_trajectory'])


        grouped = result_df[["Game","MSE", "RMSE", "predicted_tiles", "true_tiles", 'landing_error']].groupby("Game").apply(lambda group: pd.Series({
        "acc" : calculate_accuracy(group), 
        "f1" : calculate_f1_macro(group), 
        "MSE" : group["MSE"].mean(),
        "RMSE" : group["RMSE"].mean(),
        'Landing Error' : group['landing_error'].mean()}))
        #print(result_df['MSE'])

        mean_results = { "mean mse": np.mean(result_df["MSE"].tolist()), 
                        "mean rmse" : np.mean(result_df["RMSE"].tolist()),
                        "acc" : accuracy_score(result_df["predicted_tiles"], result_df["true_tiles"]), 
                        "f1" : f1_score(result_df["predicted_tiles"], result_df["true_tiles"], average='macro'),
                       'mean landing_error' : np.mean(result_df['landing_error'].tolist())}
    
    else:
        
        result_df = pd.DataFrame(list(zip(game_n, clip_n, shot_n, mse_n, rmse_n, pred_tiles, true_tiles, landing_error, trajectory_distance, start_errors, predicted_3D_traj)),
                   columns =['Game', 'Clip', "Shot Number", "MSE", "RMSE", "predicted_tiles", "true_tiles", 'landing_error', 'trajectory_distance', 'start_error','predicted_trajectory'])
        
        mean_start_errors = np.mean(np.array(start_errors), axis=0).tolist()
        
        grouped = result_df.groupby('Game').apply(lambda group: pd.Series({
            'acc': calculate_accuracy(group),
            'f1': calculate_f1_macro(group),
            'MSE': group['MSE'].mean(),
            'RMSE': group['RMSE'].mean(),
            'Landing Error': group['landing_error'].mean(),
            'Trajectory Distance': group['trajectory_distance'].mean(),
            'Start Error': np.sqrt(np.mean(np.array(group['start_error'].tolist()), axis=0)).tolist()
        }))
        
        print(grouped['Start Error'])
        
         # Grouped metrics calculation
        #grouped = result_df.groupby('Game').apply(lambda group: pd.Series({
        #    'acc': calculate_accuracy(group),
        #    'f1': calculate_f1_macro(group),
        #    'MSE': group['MSE'].mean(),
        #    'RMSE': group['RMSE'].mean(),
        #    'Landing Error': group['landing_error'].mean(),
        #    'Trajectory Distance': group['trajectory_distance'].mean(),
        #    'Start Error': group['start_error'].apply(lambda x: np.mean(x))
        #}))
        

        mean_results = {
            'mean mse': np.mean(result_df['MSE'].tolist()),
            'mean rmse': np.mean(result_df['RMSE'].tolist()),
            'acc': accuracy_score(result_df['predicted_tiles'], result_df['true_tiles']),
            'f1': f1_score(result_df['predicted_tiles'], result_df['true_tiles'], average='macro'),
            'mean landing error': np.mean(result_df['landing_error'].tolist()),
            'mean trajectory distance': np.mean(result_df['trajectory_distance'].tolist()),
            'mean start error': mean_start_errors
        }
        print('could find mean')

            
    return result_df, grouped, mean_results
    #return outputs, rmse_scores, mse_scores, true_trajectories, shot_ids, camera_matrices, distortion_coefficients, translation_vectors, rotational_matrices
        

# Training and inference

## Using Trajectory + Corners

### without spin

In [12]:
path = 'with_corners/without_spin/'

if not os.path.exists(path):
    os.makedirs(path)

start = time()
model, loss = train_syn(num_epochs = 25,
                        model_ = CustomModel,
                        lr = 0.005,
                        use_court = True, 
                        use_cam_params = False,
                        use_positions = False,
                        spin = False)

print(f'time it took to train : {time()-start}')
## SAVE MODEL

torch.save(model.state_dict(), os.path.join(path,'model.pth'))

# Synthetic
start = time()
df_syn, grouped_syn, mean_results_syn = predict_NN(data_loader = syn_loader_val_NN, 
                                                   model = model,
                                                   spin = False,
                                                   use_court = True, 
                                                   use_cam_params = False, 
                                                   use_positions = False, 
                                                   synthetic_data = True)

df_syn.to_csv(os.path.join(path, 'all_shots_synthetic.csv'))
grouped_syn.to_csv(os.path.join(path, 'by_game_synthetic.csv'))
with open(os.path.join(path,"mean_results_synthetic.json"), 'w') as f:
    json.dump(mean_results_syn, f)
    
print(f'time it took to test on synthetic : {time()-start}')

# true all
start = time()
df_true, grouped_true, mean_results_true = predict_NN(data_loader = real_all_loader_NN_true, 
                                                      model = model,
                                                      spin=False,
                                                      use_court = True, 
                                                      use_cam_params = False, 
                                                      use_positions = False, 
                                                      synthetic_data = False)

df_true.to_csv(os.path.join(path, 'all_shots_true.csv'))
grouped_true.to_csv(os.path.join(path, 'by_game_true.csv'))
with open(os.path.join(path,"mean_results_true.json"), 'w') as f:
    json.dump(mean_results_true, f)

print(f'time it took to test on real true : {time()-start}')
    
    
# predicted all
start=time()
df_pred, grouped_pred, mean_results_pred = predict_NN(data_loader = real_all_loader_NN_pred, 
                                                      model = model,
                                                      spin=False,
                                                      use_court = True, 
                                                      use_cam_params = False, 
                                                      use_positions = False, 
                                                      synthetic_data = False)
print(f'time it took to test on real predicted : {time()-start}')

df_pred.to_csv(os.path.join(path, 'all_shots_predicted.csv'))
grouped_pred.to_csv(os.path.join(path, 'by_game_predicted.csv'))
with open(os.path.join(path,"mean_results_predicted.json"), 'w') as f:
    json.dump(mean_results_pred, f)

tensor([0.1558, 0.2370, 0.2118, 0.5699, 0.2445, 0.1817], device='cuda:0')
Epoch 1/25, Train Loss: 0.0025
Epoch 1/25, Validation Loss: 0.3014474994427449


tensor([0.1625, 0.2383, 0.2053, 0.5602, 0.2338, 0.1766], device='cuda:0')
Epoch 2/25, Train Loss: 0.0016
Epoch 2/25, Validation Loss: 0.2916487721172539


tensor([0.1530, 0.2319, 0.2028, 0.5484, 0.2288, 0.1797], device='cuda:0')
Epoch 3/25, Train Loss: 0.0014
Epoch 3/25, Validation Loss: 0.2788095973633431


tensor([0.1474, 0.2231, 0.1974, 0.4881, 0.2146, 0.1757], device='cuda:0')
Epoch 4/25, Train Loss: 0.0011
Epoch 4/25, Validation Loss: 0.20053563367676092


tensor([0.1352, 0.2199, 0.1932, 0.4490, 0.2076, 0.1712], device='cuda:0')
Epoch 5/25, Train Loss: 0.0009
Epoch 5/25, Validation Loss: 0.1935675079758103


tensor([0.1278, 0.2149, 0.1910, 0.4176, 0.2011, 0.1686], device='cuda:0')
Epoch 6/25, Train Loss: 0.0009
Epoch 6/25, Validation Loss: 0.18219285357642817


tensor([0.1225, 0.2103, 0.1888, 0.3948, 0.1958, 0.1661], device='cuda:0')
Epoch 7/25, Train Loss: 0.0008
Epoch 7/25, Validation Loss: 0.17935922016968597


tensor([0.1177, 0.2070, 0.1875, 0.3803, 0.1917, 0.1647], device='cuda:0')
Epoch 8/25, Train Loss: 0.0008
Epoch 8/25, Validation Loss: 0.18368005833110293


tensor([0.1133, 0.2046, 0.1862, 0.3678, 0.1893, 0.1636], device='cuda:0')
Epoch 9/25, Train Loss: 0.0007
Epoch 9/25, Validation Loss: 0.18145103833159884


tensor([0.1089, 0.2021, 0.1848, 0.3522, 0.1864, 0.1625], device='cuda:0')
Epoch 10/25, Train Loss: 0.0007
Epoch 10/25, Validation Loss: 0.16453899120962298


tensor([0.1058, 0.2001, 0.1835, 0.3406, 0.1838, 0.1613], device='cuda:0')
Epoch 11/25, Train Loss: 0.0007
Epoch 11/25, Validation Loss: 0.16605232857369087


tensor([0.1034, 0.1986, 0.1826, 0.3310, 0.1817, 0.1603], device='cuda:0')
Epoch 12/25, Train Loss: 0.0007
Epoch 12/25, Validation Loss: 0.16765463513297005


tensor([0.1013, 0.1968, 0.1814, 0.3216, 0.1795, 0.1595], device='cuda:0')
Epoch 13/25, Train Loss: 0.0007
Epoch 13/25, Validation Loss: 0.1608778314815985


tensor([0.1001, 0.1952, 0.1804, 0.3154, 0.1775, 0.1586], device='cuda:0')
Epoch 14/25, Train Loss: 0.0007
Epoch 14/25, Validation Loss: 0.1669247287350732


tensor([0.0983, 0.1939, 0.1796, 0.3084, 0.1759, 0.1582], device='cuda:0')
Epoch 15/25, Train Loss: 0.0007
Epoch 15/25, Validation Loss: 0.16134503242131826


tensor([0.0965, 0.1934, 0.1791, 0.3018, 0.1749, 0.1579], device='cuda:0')
Epoch 16/25, Train Loss: 0.0007
Epoch 16/25, Validation Loss: 0.16369699948542826


tensor([0.0948, 0.1924, 0.1786, 0.2968, 0.1736, 0.1575], device='cuda:0')
Epoch 17/25, Train Loss: 0.0007
Epoch 17/25, Validation Loss: 0.1629887529321619


tensor([0.0937, 0.1916, 0.1783, 0.2936, 0.1725, 0.1571], device='cuda:0')
Epoch 18/25, Train Loss: 0.0007
Epoch 18/25, Validation Loss: 0.16901002743759672


tensor([0.0926, 0.1909, 0.1778, 0.2884, 0.1716, 0.1568], device='cuda:0')
Epoch 19/25, Train Loss: 0.0007
Epoch 19/25, Validation Loss: 0.15942550732477292


tensor([0.0918, 0.1902, 0.1772, 0.2859, 0.1708, 0.1564], device='cuda:0')
Epoch 20/25, Train Loss: 0.0007
Epoch 20/25, Validation Loss: 0.1679753177874797


tensor([0.0909, 0.1896, 0.1768, 0.2824, 0.1699, 0.1562], device='cuda:0')
Epoch 21/25, Train Loss: 0.0007
Epoch 21/25, Validation Loss: 0.16182559446708575


tensor([0.0901, 0.1891, 0.1764, 0.2795, 0.1691, 0.1557], device='cuda:0')
Epoch 22/25, Train Loss: 0.0007
Epoch 22/25, Validation Loss: 0.1632284417345717


tensor([0.0892, 0.1886, 0.1762, 0.2759, 0.1682, 0.1555], device='cuda:0')
Epoch 23/25, Train Loss: 0.0007
Epoch 23/25, Validation Loss: 0.1585601064804438


tensor([0.0886, 0.1882, 0.1758, 0.2722, 0.1675, 0.1552], device='cuda:0')
Epoch 24/25, Train Loss: 0.0007
Epoch 24/25, Validation Loss: 0.15717600890108058


tensor([0.0878, 0.1877, 0.1756, 0.2699, 0.1672, 0.1550], device='cuda:0')
Epoch 25/25, Train Loss: 0.0007
Epoch 25/25, Validation Loss: 0.16356517817523028
time it took to train : 1406.394695520401


/tmp/ipykernel_23/1157814838.py:191: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped = result_df.groupby('Game').apply(lambda group: pd.Series({


Game
game1    [0.4539912748597565, 2.1704513208998417, 0.500...
game8    [0.4153808744703075, 2.4193155211444615, 0.529...
Name: Start Error, dtype: object
could find mean
time it took to test on synthetic : 63.792314529418945


/tmp/ipykernel_23/1157814838.py:170: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped = result_df[["Game","MSE", "RMSE", "predicted_tiles", "true_tiles", 'landing_error']].groupby("Game").apply(lambda group: pd.Series({


time it took to test on real true : 15.918471574783325
time it took to test on real predicted : 13.765521764755249


/tmp/ipykernel_23/1157814838.py:170: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped = result_df[["Game","MSE", "RMSE", "predicted_tiles", "true_tiles", 'landing_error']].groupby("Game").apply(lambda group: pd.Series({


### with spin

In [13]:
path = 'with_corners/with_spin/'

if not os.path.exists(path):
    os.makedirs(path)

start = time()
model, loss = train_syn(num_epochs = 25,
                        model_ = CustomModel,
                        lr = 0.005,
                        use_court = True, 
                        use_cam_params = False,
                        use_positions = False,
                        spin = True)


print(f'time it took to train : {time()-start}')
## SAVE MODEL
torch.save(model.state_dict(), os.path.join(path,'model.pth'))
model.to(device)

# Synthetic
start = time()
df_syn, grouped_syn, mean_results_syn = predict_NN(data_loader = syn_loader_val_NN_spin, 
                                                   model = model,
                                                   spin = True,
                                                   use_court = True, 
                                                   use_cam_params = False, 
                                                   use_positions = False, 
                                                   synthetic_data = True)

print(f'time it took to test on synthetic : {time()-start}')
df_syn.to_csv(os.path.join(path, 'all_shots_synthetic.csv'))
grouped_syn.to_csv(os.path.join(path, 'by_game_synthetic.csv'))
with open(os.path.join(path,"mean_results_synthetic.json"), 'w') as f:
    json.dump(mean_results_syn, f)

# true all
start = time()
df_true, grouped_true, mean_results_true = predict_NN(data_loader = real_all_loader_NN_true, 
                                                      model = model,
                                                      spin=True,
                                                      use_court = True, 
                                                      use_cam_params = False, 
                                                      use_positions = False, 
                                                      synthetic_data = False)

print(f'time it took to test on real true : {time()-start}')
df_true.to_csv(os.path.join(path, 'all_shots_true.csv'))
grouped_true.to_csv(os.path.join(path, 'by_game_true.csv'))
with open(os.path.join(path,"mean_results_true.json"), 'w') as f:
    json.dump(mean_results_true, f)

# predicted all
start = time()
df_pred, grouped_pred, mean_results_pred = predict_NN(data_loader = real_all_loader_NN_pred, 
                                                      model = model,
                                                      spin=True,
                                                      use_court = True, 
                                                      use_cam_params = False, 
                                                      use_positions = False, 
                                                      synthetic_data = False)
print(f'time it took to test on real predicted : {time()-start}')

df_pred.to_csv(os.path.join(path, 'all_shots_predicted.csv'))
grouped_pred.to_csv(os.path.join(path, 'by_game_predicted.csv'))
with open(os.path.join(path,"mean_results_predicted.json"), 'w') as f:
    json.dump(mean_results_pred, f)



tensor([0.3099, 0.3725, 0.2529, 0.5791, 0.4411, 0.2547, 0.4700, 0.5788, 0.5768],
       device='cuda:0')
Epoch 1/25, Train Loss: 0.0037
Epoch 1/25, Validation Loss: 0.44640617435042923


tensor([0.2262, 0.3421, 0.2437, 0.5724, 0.3884, 0.2545, 0.4529, 0.5750, 0.5771],
       device='cuda:0')
Epoch 2/25, Train Loss: 0.0028
Epoch 2/25, Validation Loss: 0.41195981566970413


tensor([0.1981, 0.3032, 0.2382, 0.5688, 0.3361, 0.2531, 0.4429, 0.5745, 0.5752],
       device='cuda:0')
Epoch 3/25, Train Loss: 0.0026
Epoch 3/25, Validation Loss: 0.3936922228014147


tensor([0.1785, 0.2847, 0.2291, 0.5639, 0.3097, 0.2541, 0.4292, 0.5737, 0.5743],
       device='cuda:0')
Epoch 4/25, Train Loss: 0.0025
Epoch 4/25, Validation Loss: 0.38542883460586136


tensor([0.1817, 0.2693, 0.2236, 0.5571, 0.2861, 0.2524, 0.4196, 0.5731, 0.5727],
       device='cuda:0')
Epoch 5/25, Train Loss: 0.0024
Epoch 5/25, Validation Loss: 0.37966141587979085


tensor([0.1686, 0.2588, 0.2191, 0.5361, 0.2698, 0.2523, 0.4124, 0.5723, 0.5712],
       device='cuda:0')
Epoch 6/25, Train Loss: 0.0024
Epoch 6/25, Validation Loss: 0.3594687307203138


tensor([0.1578, 0.2497, 0.2147, 0.5098, 0.2541, 0.2516, 0.4047, 0.5718, 0.5696],
       device='cuda:0')
Epoch 7/25, Train Loss: 0.0022
Epoch 7/25, Validation Loss: 0.3436510587060774


tensor([0.1490, 0.2431, 0.2117, 0.4878, 0.2424, 0.2506, 0.3992, 0.5713, 0.5687],
       device='cuda:0')
Epoch 8/25, Train Loss: 0.0022
Epoch 8/25, Validation Loss: 0.34209547574455673


tensor([0.1416, 0.2374, 0.2088, 0.4684, 0.2328, 0.2495, 0.3943, 0.5712, 0.5678],
       device='cuda:0')
Epoch 9/25, Train Loss: 0.0021
Epoch 9/25, Validation Loss: 0.33761567441192836


tensor([0.1367, 0.2329, 0.2058, 0.4569, 0.2248, 0.2484, 0.3903, 0.5709, 0.5668],
       device='cuda:0')
Epoch 10/25, Train Loss: 0.0021
Epoch 10/25, Validation Loss: 0.3411956397262779


tensor([0.1316, 0.2293, 0.2036, 0.4446, 0.2187, 0.2475, 0.3872, 0.5708, 0.5661],
       device='cuda:0')
Epoch 11/25, Train Loss: 0.0021
Epoch 11/25, Validation Loss: 0.33840149077209264


tensor([0.1274, 0.2259, 0.2016, 0.4338, 0.2132, 0.2466, 0.3843, 0.5704, 0.5656],
       device='cuda:0')
Epoch 12/25, Train Loss: 0.0021
Epoch 12/25, Validation Loss: 0.3358777076811404


tensor([0.1239, 0.2230, 0.2001, 0.4244, 0.2085, 0.2458, 0.3818, 0.5702, 0.5650],
       device='cuda:0')
Epoch 13/25, Train Loss: 0.0021
Epoch 13/25, Validation Loss: 0.3354973124491202


tensor([0.1203, 0.2207, 0.1989, 0.4164, 0.2043, 0.2452, 0.3797, 0.5698, 0.5648],
       device='cuda:0')
Epoch 14/25, Train Loss: 0.0021
Epoch 14/25, Validation Loss: 0.3359935565574749


tensor([0.1176, 0.2188, 0.1976, 0.4085, 0.2009, 0.2445, 0.3778, 0.5695, 0.5645],
       device='cuda:0')
Epoch 15/25, Train Loss: 0.0020
Epoch 15/25, Validation Loss: 0.33419754537376195


tensor([0.1151, 0.2170, 0.1964, 0.4014, 0.1979, 0.2440, 0.3762, 0.5694, 0.5641],
       device='cuda:0')
Epoch 16/25, Train Loss: 0.0020
Epoch 16/25, Validation Loss: 0.33367132012908524


tensor([0.1130, 0.2157, 0.1956, 0.3948, 0.1953, 0.2436, 0.3747, 0.5693, 0.5638],
       device='cuda:0')
Epoch 17/25, Train Loss: 0.0020
Epoch 17/25, Validation Loss: 0.33369803589743535


tensor([0.1110, 0.2142, 0.1948, 0.3894, 0.1927, 0.2431, 0.3735, 0.5692, 0.5635],
       device='cuda:0')
Epoch 18/25, Train Loss: 0.0020
Epoch 18/25, Validation Loss: 0.3334884989906002


tensor([0.1094, 0.2129, 0.1940, 0.3842, 0.1904, 0.2427, 0.3723, 0.5692, 0.5631],
       device='cuda:0')
Epoch 19/25, Train Loss: 0.0020
Epoch 19/25, Validation Loss: 0.33319154542845647


tensor([0.1078, 0.2117, 0.1932, 0.3801, 0.1884, 0.2422, 0.3713, 0.5691, 0.5630],
       device='cuda:0')
Epoch 20/25, Train Loss: 0.0020
Epoch 20/25, Validation Loss: 0.3346016012333535


tensor([0.1065, 0.2107, 0.1926, 0.3764, 0.1866, 0.2419, 0.3703, 0.5692, 0.5627],
       device='cuda:0')
Epoch 21/25, Train Loss: 0.0020
Epoch 21/25, Validation Loss: 0.33453358347351486


tensor([0.1052, 0.2098, 0.1921, 0.3728, 0.1851, 0.2416, 0.3695, 0.5691, 0.5626],
       device='cuda:0')
Epoch 22/25, Train Loss: 0.0020
Epoch 22/25, Validation Loss: 0.33436174892090464


tensor([0.1038, 0.2090, 0.1916, 0.3690, 0.1837, 0.2413, 0.3687, 0.5690, 0.5623],
       device='cuda:0')
Epoch 23/25, Train Loss: 0.0020
Epoch 23/25, Validation Loss: 0.332288598692095


tensor([0.1028, 0.2084, 0.1913, 0.3655, 0.1826, 0.2410, 0.3679, 0.5689, 0.5623],
       device='cuda:0')
Epoch 24/25, Train Loss: 0.0020
Epoch 24/25, Validation Loss: 0.33392968451654587


tensor([0.1017, 0.2077, 0.1908, 0.3631, 0.1813, 0.2407, 0.3672, 0.5690, 0.5621],
       device='cuda:0')
Epoch 25/25, Train Loss: 0.0020
Epoch 25/25, Validation Loss: 0.334424904069385
time it took to train : 1390.5164813995361


/tmp/ipykernel_23/1157814838.py:191: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped = result_df.groupby('Game').apply(lambda group: pd.Series({


Game
game1    [0.4827139038037658, 2.4060753548425877, 0.530...
game8    [0.48753793962961867, 2.589915422113301, 0.553...
Name: Start Error, dtype: object
could find mean
time it took to test on synthetic : 73.27429008483887


/tmp/ipykernel_23/1157814838.py:170: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped = result_df[["Game","MSE", "RMSE", "predicted_tiles", "true_tiles", 'landing_error']].groupby("Game").apply(lambda group: pd.Series({


time it took to test on real true : 16.176509857177734
time it took to test on real predicted : 14.952239513397217


/tmp/ipykernel_23/1157814838.py:170: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped = result_df[["Game","MSE", "RMSE", "predicted_tiles", "true_tiles", 'landing_error']].groupby("Game").apply(lambda group: pd.Series({


## Without Corners

### without spin

In [14]:
path = 'without_corners/without_spin/'

if not os.path.exists(path):
    os.makedirs(path)

start = time()
model, loss = train_syn(num_epochs = 25,
                        model_ = CustomModel,
                        lr = 0.005,
                        use_court = False, 
                        use_cam_params = False,
                        use_positions = False,
                        spin = False)
print(f'time it took to train : {time()-start}')
## SAVE MODEL

torch.save(model.state_dict(), os.path.join(path,'model.pth'))

# Synthetic
start = time()
df_syn, grouped_syn, mean_results_syn = predict_NN(data_loader = syn_loader_val_NN, 
                                                   model = model,
                                                   spin = False,
                                                   use_court = False, 
                                                   use_cam_params = False, 
                                                   use_positions = False, 
                                                   synthetic_data = True)
print(f'time it took to test on synthetic : {time()-start}')
df_syn.to_csv(os.path.join(path, 'all_shots_synthetic.csv'))
grouped_syn.to_csv(os.path.join(path, 'by_game_synthetic.csv'))
with open(os.path.join(path,"mean_results_synthetic.json"), 'w') as f:
    json.dump(mean_results_syn, f)

# true all
start = time()
df_true, grouped_true, mean_results_true = predict_NN(data_loader = real_all_loader_NN_true, 
                                                      model = model,
                                                      spin=False,
                                                      use_court = False, 
                                                      use_cam_params = False, 
                                                      use_positions = False, 
                                                      synthetic_data = False)

print(f'time it took to test on real true : {time()-start}')

df_true.to_csv(os.path.join(path, 'all_shots_true.csv'))
grouped_true.to_csv(os.path.join(path, 'by_game_true.csv'))
with open(os.path.join(path,"mean_results_true.json"), 'w') as f:
    json.dump(mean_results_true, f)
    
    
# predicted all
start = time()
df_pred, grouped_pred, mean_results_pred = predict_NN(data_loader = real_all_loader_NN_pred, 
                                                      model = model,
                                                      spin=False,
                                                      use_court = False, 
                                                      use_cam_params = False, 
                                                      use_positions = False, 
                                                      synthetic_data = False)

print(f'time it took to test on real predicted : {time()-start}')
df_pred.to_csv(os.path.join(path, 'all_shots_predicted.csv'))
grouped_pred.to_csv(os.path.join(path, 'by_game_predicted.csv'))
with open(os.path.join(path,"mean_results_predicted.json"), 'w') as f:
    json.dump(mean_results_pred, f)

tensor([0.1598, 0.2689, 0.2193, 0.5496, 0.2440, 0.1741], device='cuda:0')
Epoch 1/25, Train Loss: 0.0023
Epoch 1/25, Validation Loss: 0.30036658894371343


tensor([0.1668, 0.2510, 0.2136, 0.5426, 0.2256, 0.1800], device='cuda:0')
Epoch 2/25, Train Loss: 0.0016
Epoch 2/25, Validation Loss: 0.2871890478842967


tensor([0.1467, 0.2418, 0.2069, 0.4722, 0.2164, 0.1754], device='cuda:0')
Epoch 3/25, Train Loss: 0.0012
Epoch 3/25, Validation Loss: 0.21539394919936722


tensor([0.1307, 0.2356, 0.2026, 0.4283, 0.2076, 0.1720], device='cuda:0')
Epoch 4/25, Train Loss: 0.0010
Epoch 4/25, Validation Loss: 0.19987461776346774


tensor([0.1226, 0.2317, 0.1989, 0.3984, 0.2004, 0.1693], device='cuda:0')
Epoch 5/25, Train Loss: 0.0009
Epoch 5/25, Validation Loss: 0.1932396244358372


tensor([0.1201, 0.2282, 0.1968, 0.3748, 0.1941, 0.1685], device='cuda:0')
Epoch 6/25, Train Loss: 0.0009
Epoch 6/25, Validation Loss: 0.18790902479274854


tensor([0.1144, 0.2248, 0.1952, 0.3575, 0.1890, 0.1676], device='cuda:0')
Epoch 7/25, Train Loss: 0.0008
Epoch 7/25, Validation Loss: 0.18241625460418495


tensor([0.1103, 0.2242, 0.1940, 0.3466, 0.1858, 0.1677], device='cuda:0')
Epoch 8/25, Train Loss: 0.0008
Epoch 8/25, Validation Loss: 0.1914957979240933


tensor([0.1066, 0.2225, 0.1930, 0.3332, 0.1831, 0.1669], device='cuda:0')
Epoch 9/25, Train Loss: 0.0008
Epoch 9/25, Validation Loss: 0.17749625323592005


tensor([0.1037, 0.2214, 0.1918, 0.3219, 0.1807, 0.1659], device='cuda:0')
Epoch 10/25, Train Loss: 0.0008
Epoch 10/25, Validation Loss: 0.1749813745956163


tensor([0.1025, 0.2197, 0.1907, 0.3131, 0.1784, 0.1650], device='cuda:0')
Epoch 11/25, Train Loss: 0.0008
Epoch 11/25, Validation Loss: 0.1744744052758088


tensor([0.1007, 0.2187, 0.1901, 0.3057, 0.1769, 0.1647], device='cuda:0')
Epoch 12/25, Train Loss: 0.0008
Epoch 12/25, Validation Loss: 0.1765736208574192


tensor([0.0993, 0.2174, 0.1894, 0.3005, 0.1757, 0.1643], device='cuda:0')
Epoch 13/25, Train Loss: 0.0007
Epoch 13/25, Validation Loss: 0.17786412464605794


tensor([0.0971, 0.2168, 0.1890, 0.2936, 0.1744, 0.1636], device='cuda:0')
Epoch 14/25, Train Loss: 0.0007
Epoch 14/25, Validation Loss: 0.17069718120871363


tensor([0.0951, 0.2158, 0.1885, 0.2879, 0.1734, 0.1631], device='cuda:0')
Epoch 15/25, Train Loss: 0.0007
Epoch 15/25, Validation Loss: 0.16988084364581751


tensor([0.0943, 0.2150, 0.1881, 0.2829, 0.1725, 0.1629], device='cuda:0')
Epoch 16/25, Train Loss: 0.0007
Epoch 16/25, Validation Loss: 0.17160264946318962


tensor([0.0941, 0.2142, 0.1874, 0.2804, 0.1716, 0.1626], device='cuda:0')
Epoch 17/25, Train Loss: 0.0007
Epoch 17/25, Validation Loss: 0.1777216385345201


tensor([0.0934, 0.2137, 0.1870, 0.2762, 0.1707, 0.1621], device='cuda:0')
Epoch 18/25, Train Loss: 0.0007
Epoch 18/25, Validation Loss: 0.16996999568230398


tensor([0.0923, 0.2129, 0.1868, 0.2728, 0.1704, 0.1618], device='cuda:0')
Epoch 19/25, Train Loss: 0.0007
Epoch 19/25, Validation Loss: 0.17144398995347926


tensor([0.0911, 0.2122, 0.1864, 0.2689, 0.1701, 0.1616], device='cuda:0')
Epoch 20/25, Train Loss: 0.0007
Epoch 20/25, Validation Loss: 0.16712252554055806


tensor([0.0906, 0.2123, 0.1863, 0.2664, 0.1695, 0.1614], device='cuda:0')
Epoch 21/25, Train Loss: 0.0007
Epoch 21/25, Validation Loss: 0.1757498725846007


tensor([0.0901, 0.2117, 0.1861, 0.2641, 0.1690, 0.1611], device='cuda:0')
Epoch 22/25, Train Loss: 0.0007
Epoch 22/25, Validation Loss: 0.17052670910551743


tensor([0.0898, 0.2112, 0.1859, 0.2616, 0.1686, 0.1609], device='cuda:0')
Epoch 23/25, Train Loss: 0.0007
Epoch 23/25, Validation Loss: 0.17077231165525075


tensor([0.0895, 0.2107, 0.1857, 0.2597, 0.1683, 0.1606], device='cuda:0')
Epoch 24/25, Train Loss: 0.0007
Epoch 24/25, Validation Loss: 0.1720548107011898


tensor([0.0889, 0.2105, 0.1855, 0.2590, 0.1678, 0.1604], device='cuda:0')
Epoch 25/25, Train Loss: 0.0007
Epoch 25/25, Validation Loss: 0.17796073813696164
time it took to train : 1367.9196956157684


/tmp/ipykernel_23/1157814838.py:191: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped = result_df.groupby('Game').apply(lambda group: pd.Series({


Game
game1    [0.49096329907041786, 2.4733259047882044, 0.52...
game8    [0.4765252517869483, 2.9017350342514616, 0.576...
Name: Start Error, dtype: object
could find mean
time it took to test on synthetic : 62.62806177139282


/tmp/ipykernel_23/1157814838.py:170: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped = result_df[["Game","MSE", "RMSE", "predicted_tiles", "true_tiles", 'landing_error']].groupby("Game").apply(lambda group: pd.Series({


time it took to test on real true : 14.307600975036621
time it took to test on real predicted : 13.88283896446228


/tmp/ipykernel_23/1157814838.py:170: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped = result_df[["Game","MSE", "RMSE", "predicted_tiles", "true_tiles", 'landing_error']].groupby("Game").apply(lambda group: pd.Series({


### with spin

In [15]:
path = 'without_corners/with_spin/'

if not os.path.exists(path):
    os.makedirs(path)
start = time()
model, loss = train_syn(num_epochs = 25,
                        model_ = CustomModel,
                        lr = 0.005,
                        use_court = False, 
                        use_cam_params = False,
                        use_positions = False,
                        spin = True)
print(f'time it took to train : {time()-start}')
## SAVE MODEL

torch.save(model.state_dict(), os.path.join(path,'model.pth'))

# Synthetic
start = time()
df_syn, grouped_syn, mean_results_syn = predict_NN(data_loader = syn_loader_val_NN_spin, 
                                                   model = model,
                                                   spin = True,
                                                   use_court = False, 
                                                   use_cam_params = False, 
                                                   use_positions = False, 
                                                   synthetic_data = True)
print(f'time it took to test on synthetic : {time()-start}')
df_syn.to_csv(os.path.join(path, 'all_shots_synthetic.csv'))
grouped_syn.to_csv(os.path.join(path, 'by_game_synthetic.csv'))
with open(os.path.join(path,"mean_results_synthetic.json"), 'w') as f:
    json.dump(mean_results_syn, f)

# true all
start = time()
df_true, grouped_true, mean_results_true = predict_NN(data_loader = real_all_loader_NN_true, 
                                                      model = model,
                                                      spin=True,
                                                      use_court = False, 
                                                      use_cam_params = False, 
                                                      use_positions = False, 
                                                      synthetic_data = False)
print(f'time it took to test on real true : {time()-start}')
df_true.to_csv(os.path.join(path, 'all_shots_true.csv'))
grouped_true.to_csv(os.path.join(path, 'by_game_true.csv'))
with open(os.path.join(path,"mean_results_true.json"), 'w') as f:
    json.dump(mean_results_true, f)
    
    
# predicted all
sttart = time()
df_pred, grouped_pred, mean_results_pred = predict_NN(data_loader = real_all_loader_NN_pred, 
                                                      model = model,
                                                      spin=True,
                                                      use_court = False, 
                                                      use_cam_params = False, 
                                                      use_positions = False, 
                                                      synthetic_data = False)

print(f'time it took to test on real predicted : {time()-start}')
df_pred.to_csv(os.path.join(path, 'all_shots_predicted.csv'))
grouped_pred.to_csv(os.path.join(path, 'by_game_predicted.csv'))
with open(os.path.join(path,"mean_results_predicted.json"), 'w') as f:
    json.dump(mean_results_pred, f)

tensor([0.1628, 0.4496, 0.2465, 0.5796, 0.5348, 0.2706, 0.5320, 0.5718, 0.5834],
       device='cuda:0')
Epoch 1/25, Train Loss: 0.0037
Epoch 1/25, Validation Loss: 0.46478922302658493


tensor([0.1554, 0.3640, 0.2439, 0.5731, 0.4242, 0.2628, 0.4929, 0.5768, 0.5770],
       device='cuda:0')
Epoch 2/25, Train Loss: 0.0028
Epoch 2/25, Validation Loss: 0.4108899155178586


tensor([0.1427, 0.3190, 0.2358, 0.5669, 0.3607, 0.2578, 0.4705, 0.5743, 0.5744],
       device='cuda:0')
Epoch 3/25, Train Loss: 0.0026
Epoch 3/25, Validation Loss: 0.39098481793661377


tensor([0.1395, 0.2922, 0.2325, 0.5630, 0.3163, 0.2546, 0.4540, 0.5734, 0.5731],
       device='cuda:0')
Epoch 4/25, Train Loss: 0.0025
Epoch 4/25, Validation Loss: 0.38399914873612895


tensor([0.1367, 0.2765, 0.2315, 0.5582, 0.2886, 0.2520, 0.4435, 0.5728, 0.5719],
       device='cuda:0')
Epoch 5/25, Train Loss: 0.0025
Epoch 5/25, Validation Loss: 0.38096211327088847


tensor([0.1357, 0.2668, 0.2298, 0.5483, 0.2689, 0.2512, 0.4350, 0.5722, 0.5707],
       device='cuda:0')
Epoch 6/25, Train Loss: 0.0024
Epoch 6/25, Validation Loss: 0.3731845158177453


tensor([0.1326, 0.2592, 0.2277, 0.5269, 0.2541, 0.2510, 0.4296, 0.5719, 0.5696],
       device='cuda:0')
Epoch 7/25, Train Loss: 0.0023
Epoch 7/25, Validation Loss: 0.35882634085577886


tensor([0.1290, 0.2531, 0.2273, 0.5094, 0.2433, 0.2503, 0.4256, 0.5717, 0.5686],
       device='cuda:0')
Epoch 8/25, Train Loss: 0.0022
Epoch 8/25, Validation Loss: 0.3568008332639127


tensor([0.1255, 0.2479, 0.2258, 0.4922, 0.2340, 0.2499, 0.4215, 0.5713, 0.5675],
       device='cuda:0')
Epoch 9/25, Train Loss: 0.0022
Epoch 9/25, Validation Loss: 0.34978780955881683


tensor([0.1220, 0.2440, 0.2246, 0.4755, 0.2265, 0.2491, 0.4181, 0.5710, 0.5667],
       device='cuda:0')
Epoch 10/25, Train Loss: 0.0022
Epoch 10/25, Validation Loss: 0.34609252375525396


tensor([0.1190, 0.2405, 0.2239, 0.4615, 0.2205, 0.2485, 0.4155, 0.5709, 0.5659],
       device='cuda:0')
Epoch 11/25, Train Loss: 0.0022
Epoch 11/25, Validation Loss: 0.3459375395968154


tensor([0.1162, 0.2377, 0.2235, 0.4494, 0.2153, 0.2480, 0.4133, 0.5708, 0.5655],
       device='cuda:0')
Epoch 12/25, Train Loss: 0.0022
Epoch 12/25, Validation Loss: 0.34547676186303833


tensor([0.1137, 0.2353, 0.2227, 0.4385, 0.2114, 0.2473, 0.4113, 0.5706, 0.5651],
       device='cuda:0')
Epoch 13/25, Train Loss: 0.0021
Epoch 13/25, Validation Loss: 0.34410016117869197


tensor([0.1115, 0.2332, 0.2222, 0.4296, 0.2078, 0.2469, 0.4097, 0.5705, 0.5647],
       device='cuda:0')
Epoch 14/25, Train Loss: 0.0021
Epoch 14/25, Validation Loss: 0.34512305984625946


tensor([0.1098, 0.2314, 0.2219, 0.4217, 0.2046, 0.2465, 0.4081, 0.5703, 0.5643],
       device='cuda:0')
Epoch 15/25, Train Loss: 0.0021
Epoch 15/25, Validation Loss: 0.3441332812244828


tensor([0.1081, 0.2297, 0.2215, 0.4143, 0.2018, 0.2461, 0.4066, 0.5701, 0.5640],
       device='cuda:0')
Epoch 16/25, Train Loss: 0.0021
Epoch 16/25, Validation Loss: 0.3428441141102765


tensor([0.1065, 0.2283, 0.2211, 0.4077, 0.1996, 0.2459, 0.4057, 0.5699, 0.5638],
       device='cuda:0')
Epoch 17/25, Train Loss: 0.0021
Epoch 17/25, Validation Loss: 0.34384979267378113


tensor([0.1051, 0.2270, 0.2208, 0.4024, 0.1973, 0.2455, 0.4046, 0.5698, 0.5635],
       device='cuda:0')
Epoch 18/25, Train Loss: 0.0021
Epoch 18/25, Validation Loss: 0.34392491707930695


tensor([0.1041, 0.2259, 0.2206, 0.3972, 0.1955, 0.2452, 0.4039, 0.5697, 0.5632],
       device='cuda:0')
Epoch 19/25, Train Loss: 0.0021
Epoch 19/25, Validation Loss: 0.34350172249046534


tensor([0.1029, 0.2251, 0.2205, 0.3925, 0.1936, 0.2449, 0.4030, 0.5696, 0.5630],
       device='cuda:0')
Epoch 20/25, Train Loss: 0.0021
Epoch 20/25, Validation Loss: 0.3434254736513705


tensor([0.1019, 0.2242, 0.2202, 0.3882, 0.1922, 0.2447, 0.4023, 0.5695, 0.5628],
       device='cuda:0')
Epoch 21/25, Train Loss: 0.0021
Epoch 21/25, Validation Loss: 0.34309370292199626


tensor([0.1010, 0.2234, 0.2199, 0.3847, 0.1906, 0.2445, 0.4015, 0.5695, 0.5628],
       device='cuda:0')
Epoch 22/25, Train Loss: 0.0021
Epoch 22/25, Validation Loss: 0.3441159926556252


tensor([0.1002, 0.2226, 0.2197, 0.3810, 0.1892, 0.2443, 0.4008, 0.5694, 0.5627],
       device='cuda:0')
Epoch 23/25, Train Loss: 0.0021
Epoch 23/25, Validation Loss: 0.34303052199853434


tensor([0.0992, 0.2219, 0.2194, 0.3778, 0.1879, 0.2442, 0.4003, 0.5693, 0.5626],
       device='cuda:0')
Epoch 24/25, Train Loss: 0.0021
Epoch 24/25, Validation Loss: 0.34293890402123733


tensor([0.0984, 0.2213, 0.2192, 0.3746, 0.1868, 0.2440, 0.3997, 0.5692, 0.5625],
       device='cuda:0')
Epoch 25/25, Train Loss: 0.0021
Epoch 25/25, Validation Loss: 0.3424751951887801
time it took to train : 1400.0312411785126


/tmp/ipykernel_23/1157814838.py:191: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped = result_df.groupby('Game').apply(lambda group: pd.Series({


Game
game1    [0.5047751067904196, 2.567980616027132, 0.6003...
game8    [0.5163913466581813, 2.7886746255841186, 0.704...
Name: Start Error, dtype: object
could find mean
time it took to test on synthetic : 73.0206732749939


/tmp/ipykernel_23/1157814838.py:170: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped = result_df[["Game","MSE", "RMSE", "predicted_tiles", "true_tiles", 'landing_error']].groupby("Game").apply(lambda group: pd.Series({


time it took to test on real true : 15.670043706893921
time it took to test on real predicted : 30.85152530670166


/tmp/ipykernel_23/1157814838.py:170: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped = result_df[["Game","MSE", "RMSE", "predicted_tiles", "true_tiles", 'landing_error']].groupby("Game").apply(lambda group: pd.Series({


# Clean output

In [16]:
import shutil
shutil.rmtree('/kaggle/working/TennisTrajectoryReconstruction')

# Fine Tune Model

In [17]:
import torch
import numpy as np
import cv2
import torch
import torch.nn as nn
import torch
import torch.nn as nn

def batch_loss(output, mtx, dist, rvecs, tvecs, rotation_matrix, inputs):
    

        
    loss = 0
    

    batch = output.shape[0]
    
    for i in range(batch):
        curr_input = inputs[i]
        
        mask = curr_input != -1
        non_padded_input = curr_input[mask].view(-1,2)
        
        N = non_padded_input.shape[0]

        mse_loss = nn.MSELoss()

        traj = create_3d_trajectory(output[i].view(1, 6), N)

        points_2d = project_points_torch(traj, rotation_matrix[i], tvecs[i], mtx[i],dist[i])
        
        points_2d[:, 0] = points_2d[:,0] / 1280
        points_2d[:, 1] = points_2d[:,1] / 720

        
        rmse = torch.sqrt(mse_loss(points_2d, non_padded_input))
        #loss_components['RMSE'].append(rmse.item())
        loss += rmse
   

    return loss / batch

In [18]:
def fine_tune(num_epochs : int, lr : float, data_loader : DataLoader, use_court : bool, use_cam_params : bool, model):
    
    input_size = 100
    output_size = 6
    
    if use_court:
        input_size += 4*2
    if use_cam_params:
        input_size += 3*3 + 3 + 3*3 + 5
    
    losses = []


    #model = model_(input_size, output_size)
    
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)
    scheduler = StepLR(optimizer, step_size=2, gamma=0.5)

    # Iterate over epochs
    for epoch in range(num_epochs):
        model.train()  # Set the model to training mode
        running_loss = 0.0
        


        # Iterate over batches in the train_loader
        for batch in tqdm(data_loader, desc=f'Epoch {epoch + 1}/{num_epochs}', leave=False):

            projection, mtx, dist, rvecs, tvecs, rotation_matrix, court_corners, shot_id_ = batch
            
            
            concatted_input = projection.view(-1, 2*50)
            
            if use_court:
                concatted_court = court_corners.view(-1, 4*2)
                concatted_input = torch.cat((concatted_court, concatted_input), dim=1)
            if use_cam_params:
                camera_matrix = mtx.view(-1, 3*3)
                translation_matrix = tvecs.view(-1, 3)
                rotation = rotation_matrix.view(-1, 3*3)
                distortion = dist.view(-1, 5)
                concatted_params = torch.cat((camera_matrix, translation_matrix, rotation, distortion), dim=1)
                concatted_input = torch.cat((concatted_params, concatted_input), dim=1)

            optimizer.zero_grad()  # Zero the gradients

            # Forward pass
            outputs = model(concatted_input.float())

            # Calculate loss
            loss = batch_loss( outputs, mtx, dist, rvecs, tvecs, rotation_matrix, projection)

            # Backward pass
            loss.backward()

            # Update weights
            optimizer.step()

            # Update running loss
            running_loss += loss.item()
            
        scheduler.step()
        # Print average loss for the epoch
        epoch_loss = running_loss / len(train_loader.dataset)
        losses.append(epoch_loss)
        print(f'Epoch {epoch + 1}/{num_epochs}, Loss: {epoch_loss:.4f}')
    return model, losses
    

In [19]:
#num_epochs : int, lr : float, data_loader : DataLoader, use_court : bool, use_cam_params : bool, model


#model, loss = fine_tune(num_epochs = 20,
#                       lr = 0.01,
#                       data_loader = real_train_loader_NN,
#                       use_court = True,
#                       use_cam_params = False,
#                       model=model)


# Inference

In [20]:
def plot_shots(starting_params : list(), true_trajectories : list(), shot_ids : list, cam_matrices : list(), 
               dist_coeffs : list(), tvecs : list(), rot_matrices : list(), df : pd.DataFrame(), nr_shots : int):
    
    court_length, court_width, half_court_length, half_court_width, net_height_middle, net_height_sides = get_court_dimension()
    
    if nr_shots > len(shot_ids):
        print('number of shots is too high')
        return None
    
    for j in range(nr_shots):
        
        shot_id = shot_ids[j]
        game = df.iloc[shot_id]["game"]
        clip = df.iloc[shot_id]["clip"]
        #start = df.iloc[shot_id]["start"]
        start = 0
        formatted_number = "{:04d}.jpg".format(start)
        
        preds = starting_params[j]
        labels = true_trajectories[j][0].cpu()
        
        N = len(labels)
        
        # Find relevant camera parameters
        camera_matrix = cam_matrices[j]
        dist = dist_coeffs[j]
        translation_vec = tvecs[j]
        rotation_matrix = rot_matrices[j]
        
        # Make 3d trajectory and project down again
        new_traj = create_3d_trajectory(preds.view(1, 6), N)
        projected_path = project_points_torch(new_traj, rotation_matrix, translation_vec, camera_matrix, dist).detach().cpu().numpy()
        
        
        image_path = f"/kaggle/input/tracknet-tennis/Dataset/{game}/{clip}/{formatted_number}"
        
        #print("avg distance", mse(projected_path, labels))
        
        img = cv2.imread(image_path)
        

        fig, axs = plt.subplots(1, 2, figsize=(10, 5))
        
        traj_pred = new_traj.cpu().numpy()
        
        #print('New Trajectory : ', projected_path)
        
        print(f'SHOT ID : {shot_id}\n GAME : {game}\n CLIP : {clip}')
        
        axs[0].imshow(img)
        for i in range(len(projected_path)):
            s = (i + 1) * 2 
#             print(s)
            axs[0].scatter(projected_path[i, 0], projected_path[i, 1], s=s, color="green", label="Reprojected Shot") 
            axs[0].scatter(labels[i,0], labels[i, 1], s=s, color="red", label="True Shot")
            axs[0].set_title("Reprojection on real shot")
        
        
        
        
        
        

        # Plot the trajectory
        axs[1] = fig.add_subplot(122, projection='3d')
        for i in range(len(traj_pred)):
            s = (i + 1) * 2  # Increase size with each iteration
            color = 'green' if traj_pred[i, 2] > 0 else 'black'
            axs[1].scatter(traj_pred[i, 0], traj_pred[i, 1], traj_pred[i, 2], s=s, c=color)        
        
        axs[1].set_xlabel('X')
        axs[1].set_ylabel('Y')
        axs[1].set_zlabel('Z')
        axs[1].set_title('Tennis Shot Trajectory with Scatter Points')
        axs[1].legend()
        plot_tennis_court(axs[1])
        
        court_length = 23.77  # meters
        court_width = 10.97  # meters
        
        axs[1].set_xlim(-half_court_length - 2, half_court_length+2)  # Set x-axis limits
        axs[1].set_ylim(-half_court_length - 2, half_court_length+2)  # Set y-axis limits
        axs[1].set_zlim(-1, 4)  # Set z-axis limits
        
#         axs[1].view_init(elev=1, azim=1)  # Change the elevation (up-down) and azimuth (left-right) angles

        
        # Adjust layout to prevent overlap
        plt.tight_layout()
        

        plt.show()

        
        fig2, axs2 = plt.subplots(1, 2, figsize=(10, 5))

        
        angles = [(0, 0), (90, -90)]
        for k in range(2):
#             print(k)
            angle = angles[k]
            
            # Plot the trajectory
            axs2[k] = fig2.add_subplot(1, 2, k+1, projection='3d')
            for i in range(len(traj_pred)):
#                 print(s)
                s = (i + 1) * 2  # Increase size with each iteration
                color = 'green' if traj_pred[i, 2] > 0 else 'black'
                axs2[k].scatter(traj_pred[i, 0], traj_pred[i, 1], traj_pred[i, 2], s=s, c=color)        

            axs2[k].set_xlabel('X')
            axs2[k].set_ylabel('Y')
            axs2[k].set_zlabel('Z')
            axs2[k].set_title('Tennis Shot Trajectory with Scatter Points')
            axs2[k].legend()
            plot_tennis_court(axs2[k])


            axs2[k].set_xlim(-half_court_length - 2, half_court_length+2)  # Set x-axis limits
            axs2[k].set_ylim(-half_court_length - 2, half_court_length+2)  # Set y-axis limits
            axs2[k].set_zlim(-1, 4)  # Set z-axis limits


            axs2[k].view_init(elev=angle[0], azim=angle[1])  # Change the elevation (up-down) and azimuth (left-right) angles
        plt.tight_layout()
        plt.show()

# 2d trajectory
# corners
# Camera Parameters
----------------------------------
# start position 3D

# GRU MODEL

class SimpleGRU(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, num_layers=1):
        super(SimpleGRU, self).__init__()
        self.hidden_size = hidden_size
        self.fc = nn.Linear(hidden_size, output_size)
        #self.fc1 = nn.Linear(non_traj_len, 128)
        #self.bn1 = nn.BatchNorm1d(128)
        #self.fc2_input_size = hidden_size + 128  # Size of concatenated tensors
        #self.fc2 = nn.Linear(self.fc2_input_size, 256)  # Define fc2 with appropriate input size
        #self.bn2 = nn.BatchNorm1d(256)
        #self.fc3 = nn.Linear(256, 128)
        #self.bn3 = nn.BatchNorm1d(128)
        #self.fc4 = nn.Linear(128, output_size)
        
        #print(hidden_size)
        
        
        #self.num_layers = num_layers
        #self.non_traj_len = non_traj_len
        
        #nn.init.constant_(self.fc1.weight, 0.1)
        #nn.init.constant_(self.fc1.bias, 0)       # Initialize biases of fc1 to zero
        ##nn.init.xavier_uniform_(self.fc2.weight)  # Xavier initialization for the weights of fc2
        #nn.init.constant_(self.fc2.weight, 0.1)
        #nn.init.constant_(self.fc2.bias, 0)       # Initialize biases of fc2 to zero
        #nn.init.xavier_uniform_(self.fc3.weight)  # Xavier initialization for the weights of fc3
        #nn.init.constant_(self.fc3.weight, 0.1)
        #nn.init.constant_(self.fc3.bias, 0)       # Initialize biases of fc3 to zero
        #nn.init.xavier_uniform_(self.fc4.weight)  # Xavier initialization for the weights of fc4
        #nn.init.constant_(self.fc4.weight, 0.1)
        #nn.init.constant_(self.fc4.bias, 0)       # Initialize biases of fc4 to zero
        
        # Define the GRU layer
        self.gru = nn.GRU(input_size, hidden_size, num_layers, batch_first=True)
        
        for name, param in self.gru.named_parameters():
            if 'weight' in name:
                nn.init.xavier_uniform_(param.data)
                #nn.init.constant_(param.data, 0.1)
            elif 'bias' in name:
                nn.init.constant_(param.data, 0.0)
        
    def forward(self, traj, h=None):

        # put camera parameters through linear layer with Relu function
        #rest = torch.relu(self.bn1(self.fc1(non_traj)))
        
        # Forward pass through the GRU layer
        out, h = self.gru(traj, h)
        
        # Take only the output at the last time step
        out = out[:, -1, :]
        
        # Pass the output through the linear layer
        out = self.fc(out)
        
        #concatenated = torch.cat((out, rest), dim=2)
        #concatenated = torch.cat((out, rest.unsqueeze(1).repeat(1, out.size(1), 1)), dim=2)
        #concatenated = concatenated.mean(dim=1)
        #concatenated = torch.relu(self.bn2(self.fc2(concatenated)))
        #concatenated = torch.relu(self.bn3(self.fc3(concatenated)))
        #concatenated = self.fc4(concatenated)
    
        
        # 
        return out

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from tqdm import tqdm

def train_syn_GRU(num_epochs : int, lr : float, hidden_size : int, num_layers : int, 
                  use_court : bool, use_cam_params : bool, use_positions : bool, model_):

    input_size = 2
    output_size = 6
    #hidden_size = hidden_size
    #num_layers = num
    

    
    losses = []

    
    model = model_(input_size, hidden_size, output_size, num_layers=1)
    
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)
    scheduler = StepLR(optimizer, step_size=2, gamma=0.5)

    # Iterate over epochs
    for epoch in range(num_epochs):
        model.train()  # Set the model to training mode
        running_loss = 0.0

        # Iterate over batches in the train_loader
        for batch in tqdm(syn_loader_GRU, desc=f'Epoch {epoch + 1}/{num_epochs}', leave=False):

            starting_params, projection,  mtx, dist, rvecs, tvecs, rotation_matrix, court_corners, start_pos, end_pos = batch
            
            
            #concatted_input = projection.view(-1, 2*50)
            
            if use_court:
                concatted_court = court_corners.view(-1, 4*2).to(starting_params.device)
                concatted_input = torch.cat((concatted_court, concatted_input), dim=1)
            if use_cam_params:
                camera_matrix = mtx.view(-1, 3*3).to(starting_params.device)
                translation_matrix = tvecs.view(-1, 3).to(starting_params.device)
                rotation = rotation_matrix.view(-1, 3*3).to(starting_params.device)
                distortion = dist.view(-1, 5).to(starting_params.device)
                concatted_params = torch.cat((camera_matrix, translation_matrix, rotation, distortion), dim=1)
                concatted_input = torch.cat((concatted_params, concatted_input), dim=1).to(starting_params.device)
            if use_positions:
                concatted_positions = torch.cat((start_pos, end_pos)).view(-1, 3*2)
                concatted_input = torch.cat((concatted_positions, concatted_input), dim=1).to(starting_params.device)
                
                

            optimizer.zero_grad()  # Zero the gradients

            # Forward pass
            outputs = model(projection.float())

            # Calculate loss
            loss = criterion(outputs, starting_params)

            # Backward pass
            loss.backward()

            # Update weights
            optimizer.step()

            # Update running loss
            running_loss += loss.item()
            
        scheduler.step()
        # Print average loss for the epoch
        epoch_loss = running_loss / len(syn_loader.dataset)
        losses.append(epoch_loss)
        print(f'Epoch {epoch + 1}/{num_epochs}, Loss: {epoch_loss:.4f}')
    return model, losses


model, loss = train_syn_GRU(num_epochs = 20, 
                            lr = 0.01,
                            hidden_size = 128,
                            num_layers = 1,
                            use_court = False, 
                            use_cam_params = False,
                            use_positions = False,
                            model_ = SimpleGRU)

def predict_GRU(data_loader : DataLoader, model):
    
    outputs = []
    predicted_squares = []
    true_squares = []
    rmse_scores = []
    mse_scores = []
    reprojection_scores = []
    true_trajectories = []
    shot_ids = []
    # Camera Parameters
    camera_matrices = []
    distortion_coefficients = []
    translation_vectors = []
    rotational_matrices = []
    
    mse_loss = nn.MSELoss()
    

    model.eval()
    with torch.no_grad():
        for batch in data_loader:
            projection, mtx, dist, rvecs, tvecs, rotation_matrix, court_corners, shot_id_, player1, player2 = batch

                
            #print(concatted_input.float().device)

            preds = model(projection.float())
            
            for i in range(len(batch[0])):
                
                camera_matrices.append(mtx[i])
                distortion_coefficients.append(dist[i])
                translation_vectors.append(tvecs[i])
                rotational_matrices.append(rotation_matrix[i])
                
                curr_input = projection[i]
                
                shot_id = shot_id_[i]
                shot_ids.append(shot_id)
                
                
                mask = curr_input != -1
                non_padded_input = curr_input[mask].view(1,-1,2)
                

                N = non_padded_input.shape[1]
                

                labels = non_padded_input#.detach().cpu().numpy()
                
                true_trajectories.append(labels)
                
                labels[:,:, 0] *= 1280
                labels[:,:,1] *= 720
                
                
                prediction = upscale_starting_params(preds[i])
                outputs.append(prediction)
                
                new_traj = create_3d_trajectory(prediction.view(1, 6), N)
                projected_path = project_points_torch(new_traj, rotation_matrix[i], tvecs[i], mtx[i], dist[i])
                
                
                mse = mse_loss(projected_path, labels[0])
                mse_scores.append(mse)
                rmse = torch.sqrt(mse)
                rmse_scores.append(rmse)
            
            
    return outputs, rmse_scores, mse_scores, true_trajectories, shot_ids, camera_matrices, distortion_coefficients, translation_vectors, rotational_matrices
        

model.to(device)
(outputs, rmse_scores, mse_scores, true_trajectories, 
 shot_ids, camera_matrices, 
 distortion_coefficients, translation_vectors, 
 rotational_matrices) = predict_GRU(data_loader = real_test_loader_GRU, 
                                    model = model)

print('MEAN RMSE : ', torch.tensor(rmse_scores).mean())
print('MEDIAN RMSE : ', torch.tensor(rmse_scores).median())